# general jekyll configuration
# NOTICE: GitHub forces to set `safe: true` in order to prohibit using plugins.
safe: false
source: .
destination: ./_site
plugins: ./_plugins
lsi: false
pygments: true
markdown: rdiscount
exclude: ['Rakefile', 'README.md']

# configuration for url/path
# `baseurl` being set without '/' at the end as absolute path is recommended.
url: http://tokkonopapa.github.com/Jekyll-Responsive-Bootstrap
baseurl: /Jekyll-Responsive-Bootstrap
permalink: /blog/:year/:month/:title/

# configuration for blog
title: My Site Title
description: Jekyll Responsive Bootstrap
author: USERNAME
email: USERNAME@example.com

#--------------------------------------------
# configuration for default.html (type: blog)
#--------------------------------------------
lang: ja
paginate: 3
columns: 2
date_format: "%B %d, %Y"
truncate_len: 200

# configuration for header.html
# NOTICE: `index.html` should be omitted.
navbar_list:
- name: Blog
  link: /
  dropdown: &dropdown
  - name: Archives
    link: /blog/archives.html
  - name: Categories
    link: /blog/categories.html
  - name: Tags
    link: /blog/tags.html
- name: Project
  link: /project/
- name: About
  link: /about.html

# configuration for asides.html
# CAUTION: `themes` should be false to put the 'script.html` at the bottom.
asides:
    about: true
    search: true
    themes: true
    recent_posts: true
    archive_tabs: true
    tweets: true

# configuration for asides/recent_posts.html
recent_posts: 5

# configration for bootstrap and color theme
# Default, Amelia, United, Superhero, Spruce, Spacelab, 
# Slate, Simplex, Readable, Journal, Cyborg, Cerulean
#bootstrap: bootstrap-2.0.4
bootstrap: bootstrap-2.1.0
color_theme: Default

#-----------------------------------------------
# configuration for socials, uncomment to enable
#-----------------------------------------------
# feedburner:
#   id: YOUR_SITE_ID

disqus:
    short_name: tokkonopapa #USERNAME
    comment_count: true
    developer: 0

google_analytics:
    account: UA-20543951-2 #UA-XXXXX-X

google_plus_one:
    size: medium

# `xfbml` will break some styles on android 2.3 native browser (Optimus L-01D).
# `locale`: ja_JP, en_US, es_LA, fr_FR, de_DE, it_IT, zh_CN, ko_KR, ...
facebook:
    xfbml: false
    locale: ja_JP

twitter:
    username: tokkonopapa
    count: 5
    show_replies: false
    show_follower_count: false
    follow_button: true
    tweet_button: true

# github:
#    username: USERNAME

hatena: true
