# general jekyll configuration
# NOTICE: GitHub forces to set `safe: true` in order to prohibit using plugins.
safe: false
source: .
destination: ./_site
plugins: ./_plugins
lsi: true
pygments: true
markdown: rdiscount
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', 'vender']

# configuration for url/path
# `baseurl` being set as absolute path without '/' at the end is recommended.
url: http://tokkono.github.com
baseurl: 

# configuration for permalink
# `permalink`: none, pretty or /blog/:categories/:title.html
permalink: /blog/:year/:month/:title/

# configuration for site
title: My Site Title
description: Jekyll Responsive Bootstrap
author: USERNAME
email: USERNAME@example.com

# configuration for blog
lang: ja
paginate: 7
columns: 3
date_format: "%B %d, %Y"
truncate_len: 200

# configuration for asides/recent_posts.html
recent_posts: 5

# configuration for header.html
navbar_list:
- name: Blog
  link: /
  dropdown: &dropdown
  - name: Archives
    link: /blog/archives.html
  - name: Categories
    link: /blog/categories.html
  - name: Tags
    link: /blog/tags.html
- name: Project
  link: /project/
- name: About
  link: /about.html

# configuration for asides.html
# CAUTION: `themes` should be false to put the 'script.html` at the bottom.
asides:
    about: true
    search: true
    themes: true
    recent_posts: true
    archive_tabs: true
    tweets: true
    github: false

# configration for bootstrap and color theme
# Default, Amelia, United, Superhero, Spruce, Spacelab, 
# Slate, Simplex, Readable, Journal, Cyborg, Cerulean
bootstrap: bootstrap-2.1.0
color_theme: Default

# configuration for pygments
# `pygments_color`:
# autumn, borland, bw, colorful, default, emacs, friendly, fruity,
# github, manni, monokai, murphy, native, pastie, perldoc, tango, trac, vs
pygments_color: github

#-----------------------------------
# configuration for 3rd party script
#-----------------------------------
disqus:
    short_name: USERNAME
    comment_count: true
    developer_mode: true

#feedburner:
#    id: YOUR_SITE_ID

#google_analytics:
#    account: UA-XXXXX-X

google_plus_one:
    size: medium

# `xfbml` will break some styles on android 2.3 native browser (Optimus L-01D).
# `locale`: ja_JP, en_US, es_LA, fr_FR, de_DE, it_IT, zh_CN, ko_KR, ...
facebook:
    xfbml: false
    locale: ja_JP

twitter:
    username: twitterapi
    count: 5
    exclude_replies: true
    show_screen_name: true
    show_follower_count: false

#github:
#    username: USERNAME
#    count: 5

#hatena: true
