# standard jekyll configuration on GitHub
safe: true
source: .
destination: ./_site
plugins: ./_plugins
lsi: false
pygments: true
markdown: rdiscount
exclude: ['Rakefile', 'README.md']

# configuration for url/path
# `baseurl` being set as a path from the root is recommended.
url: http://USERNAME.github.com
baseurl: /
permalink: /blog/:year/:month/:title/

# configuration for blog
title: My Site Title
description: Jekyll Responsive Bootstrap
author: USERNAME
email: USERNAME@example.com

#--------------------------------------------
# configuration for default.html (type: blog)
#--------------------------------------------
lang: ja
paginate: 4
columns: 3
date_format: "%B %d, %Y"
truncate_len: 200

# configuration for navbar.html
navbar_list:
- text: Blog
  type: blog
  url: index.html
  dropdown: &dropdown
  - text: Archives
    url: blog/archives.html
  - text: Categories
    url: blog/categories.html
  - text: Tags
    url: blog/tags.html
- text: Project
  url: project/index.html
- text: About
  url: about.html

# configuration for asides.html
asides:
    about: true
    search: true
    themes: true
    recent_posts: true
    archive_tabs: true
    tweets: true

# configuration for asides/recent_posts.html
recent_posts: 5

# configration for bootstrap and color theme
# Default, Amelia, United, Superhero, Spruce, Spacelab, 
# Slate, Simplex, Readable, Journal, Cyborg, Cerulean
bootstrap: bootstrap-2.0.4
color_theme: Default

#-----------------------------------------------
# configuration for socials, uncomment to enable
#-----------------------------------------------
# feedburner:
#   id: YOUR_SITE_ID

disqus:
    short_name: USERNAME
    comment_count: true

google_analytics:
    account: UA-XXXXX-X

google_plus_one:
    size: medium

# `locale`: ja_JP, en_US, es_LA, fr_FR, de_DE, it_IT, zh_CN, ko_KR, ...
facebook:
    locale: ja_JP

twitter:
    username: twitter
    count: 5
    show_replies: false
    show_follower_count: false
    follow_button: true
    tweet_button: true

# github:
#    username: USERNAME

# hatena: true
