# standard jekyll configuration
#safe: false
auto: true
source: .
destination: ./_site
plugins: ./_plugins
#lsi: false
pygments: true
markdown: rdiscount
exclude: ['Rakefile', 'README.md']

# configuration required for some pages
lang: ja
url: http://USERNAME.github.com

# configuration for blog
baseurl: /
title: My Site Title
description: Jekyll Responsive Bootstrap
author: USERNAME
email: USERNAME@example.com
permalink: /blog/:year/:month/:title/

# configuration for navbar.html
navigation:
- text: Blog
  url: index.html
  type: blog
- text: Project
  url: project.html
- text: About
  url: about.html

#---------------------------------------
# configuration for default (type: blog)
#---------------------------------------
paginate: 10
page_columns: 3
asides: [asides/about.html, asides/search.html, asides/styles.html, asides/recent_posts.html, asides/tag_clouds.html, asides/tweets.html]

# configuration for asides/recent_posts.html
recent_posts: 5

# configration for color theme
# Default, Amelia, United, Superhero, Spruce, Spacelab, Slate, Simplex, Readable, Journal, Cyborg, Cerulean
color_theme: Default

# configuration for JavaScript
# if you use 'asides/styles.html' then set it as 'false'
js_bottom: false

# configuration for ehancements, uncomment to enable

disqus:
    shortname: tokkonopapa
    comment_count: false

google_analytics:
    account: UA-XXXXX-X

google_plus_one:
    size: medium

# feedburner:
#   id: feedburnerid

twitter:
    username: tokkonopapa
    count: 5
    show_replies: false
    show_follower_count: false
    follow_button: true
    tweet_button: true

hatena: true

# github:
#   username: ghusername
